# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25aa4998c6afbb0e7e9884cb7df917f0e0c07f8f1b571305a09d82c2871c951ec68dd95ce631c0652208aefe9a604170b5eba18ec8231850237e43d8b07bcb76

test:
  secret_key_base: 42fb6634e100d4d34d28e0b4778cadc32460bf888f0e691672e247184d1eee30deea022bcf2f697a00960defe8d44a58bc3b025996ad0b30c2cf677e5811913a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
